services:

  #
  # DocumentAtom MCP Server
  # Requires a DocumentAtom backend
  # See https://hub.docker.com/r/jchristn77/documentatom
  # and https://github.com/jchristn/DocumentAtom
  #

  documentatom-mcp:
    container_name: 'documentatom-mcp'
    image: 'jchristn77/documentatom-mcp:v1.1.0'
    network_mode: 'host'
    stdin_open: true
    tty: true
    volumes:
      - ./documentatom.json:/app/documentatom.json
      - ./logs/:/app/logs/
      - ./backups/:/app/backups/
    healthcheck:
      test: curl --fail http://localhost:8200
